services:
  nginx:
    image: nginx:1.27-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:80"
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "10MB"

  api01: &api
    hostname: api01
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - db:/db
    networks:
      - rinha
      - payment-processor
    environment:
      - PORT=8080
      - DATABASE_PATH=/db/database1.db
      - DATABASE_POOL_SIZE=10
      - WORKER_POOL_SIZE=4
      - DEFAULT_SERVICE_NAME=default
      - DEFAULT_SERVICE_URL=http://payment-processor-default:8080
      - FALLBACK_SERVICE_NAME=fallback
      - FALLBACK_SERVICE_URL=http://payment-processor-fallback:8080
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: "170MB"

  api02:
    <<: *api
    hostname: api02
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - DATABASE_PATH=/db/database1.db
      - DATABASE_POOL_SIZE=10
      - WORKER_POOL_SIZE=4
      - DEFAULT_SERVICE_NAME=default
      - DEFAULT_SERVICE_URL=http://payment-processor-default:8080
      - FALLBACK_SERVICE_NAME=fallback
      - FALLBACK_SERVICE_URL=http://payment-processor-fallback:8080

volumes:
  db:

networks:
  rinha:
    name: rinha
    driver: bridge
  payment-processor:
    external: true
