services:
  nginx:
    image: nginx:1.25-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    networks:
      - rinha
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "30MB"
  
  api01: &api
    hostname: api01
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    networks:
      - rinha
      - payment-processor
    volumes:
      - db:/db
    environment:
      - PORT=8080
      - DATABASE_PATH=/db/database.db
      - DATABASE_POOL_SIZE=5
      - WORKER_POOL_SIZE=2
      - DEFAULT_SERVICE_NAME=default
      - DEFAULT_SERVICE_URL=http://payment-processor-default:8080
      - FALLBACK_SERVICE_NAME=fallback
      - FALLBACK_SERVICE_URL=http://payment-processor-fallback:8080
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "160MB"

  api02:
    <<: *api
    hostname: api02
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - DATABASE_PATH=/db/database.db
      - DATABASE_POOL_SIZE=5
      - WORKER_POOL_SIZE=2
      - DEFAULT_SERVICE_NAME=default
      - DEFAULT_SERVICE_URL=http://payment-processor-default:8080
      - FALLBACK_SERVICE_NAME=fallback
      - FALLBACK_SERVICE_URL=http://payment-processor-fallback:8080
    depends_on:
      - api01

volumes:
  db:

networks:
  rinha:
    name: rinha
    driver: bridge
  payment-processor:
    external: true
